version: "3.8"

services:
  app-lambda:
    build:
      context: .
      dockerfile: deployment/Dockerfile.deploy
    environment:
      - TYPE_HANDLER=LAMBDA
    ports:
      - "9000:8080"
  app-api:
    build:
      context: .
      dockerfile: deployment/Dockerfile.local
    environment:
      - TYPE_HANDLER=API
    ports:
      - "9000:8080"
